# Part of `travis-lazarus` (https://github.com/nielsAD/travis-lazarus)
# License: MIT

language: pascal
sudo: required
dist: trusty

os:
  - linux

env:
  global:
    - WINEPREFIX=~/.winelaz
    - DISPLAY=:99.0
  matrix:
    - LAZ_PKG=true  # Use the latest version from the default package manager
    - LAZ_VER=1.8.4

matrix:
  include:
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win32 LAZ_OPT="--os=win32 --cpu=i386 -dTRAVIS_CI"
    - os: linux
      env: LAZ_VER=1.8.2 LAZ_ENV=wine WINEARCH=win64 LAZ_OPT="--os=linux --cpu=x86_64 -dTRAVIS_CI"

before_install:
  # Start virtual display server
  - Xvfb $DISPLAY &

install:
  - sudo aptitude install fpc fpc-source lcl
  - sudo aptitude install lazarus
  		  
script:
  - ls -1 ./pck/*
  - lazbuild $LAZ_OPT ./pck/paxjson_package.lpk
  - lazbuild $LAZ_OPT ./pck/tests.lpi               
  - ls -1 ./bin/*
  - $LAZ_ENV ./bin/i386/tests --all --format=plain 
  - $LAZ_ENV ./bin/x86_64/tests --all --format=plain

notifications:
  email:
    on_success: false
    on_failure: change
